apiVersion: v1
kind: Service
metadata:
  name: flask-image-editor-service
spec:
  selector:
    app: flask-image-editor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
